const products = [
    {
        id: 1,
        name: "Blend",
        price: "$5.500", 
        image: "./blend.png",
        description: "Un blend 85% Malbec, 15% Cabernet con uvas de primera calidad, cosechadas a mano, por la mañana, a bajas temperaturas, en cajas de 20 kg. cada una, y crianza de 12 meses en barrica de roble francés 50% de primer uso y 50% de segundo uso.",
        rating: 4.8,
        reviews: 100,
        category: "vinos",
        tags: ["vino", "blend", "mendoza"],
    },
    {
        id: 2,
        name: "Cabernet Sauvignon", 
        price: "$5.500", 
        image: "./cabernet-sauvignon.png",
        description: "Aroma intenso, con un carácter frutal muy marcado y notas piracínicas de pimiento. En boca es intenso, maduro con taninos firmes y maduros, buena acidez y final largo y agradable.",
        rating: 4.5,
        reviews: 100,
        category: "vinos",
        tags: ["vino", "cabernet sauvignon", "cafayate"],
    },
    {
        id: 3,
        name: "Malbec", 
        price: "$5.500", 
        image: "./malbec.png",
        description: "Un vino con todas las características del Malbec: colores violáceos intensos, oscuros y brillantes. En nariz, frutos rojos, frutillas, algo de cerezas, notas de violetas y lilas que se presentan con sutileza, igual que los aromas a vainilla y tostados aportados por su paso por madera. En boca es un vino complejo, con personalidad, buena estructura y un final muy agradable.",
        rating: 4.9,
        reviews: 100,
        category: "vinos",
        tags: ["vino", "malbec", "cafayate"],
    },
];